added interp-spectra.py

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -88,6 +88,15 @@ else
 fi
 
 ################################################################################
+# check for keys
+################################################################################
+
+if ! [ -f enlighten/keys.py ]
+then
+    echo "WARNING: keys.py not found"
+fi
+
+################################################################################
 # render documentation 
 ################################################################################
 
